name: eyepetizer
description: Use the API provided by Eyepetizer

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_splash_screen: ^0.3.0
  fluttertoast: ^8.0.7
  http: ^0.13.3
  provider: ^5.0.0
  get: ^4.3.0
  flutter_swiper: ^1.1.6
  extended_image: ^4.1.0
  pull_to_refresh: ^2.0.0
  flustars: ^2.0.1
  share_plus: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
